package com.br.framework.core.enumerator;

public enum FrameComponent {
    FRAME_CONFIG,
    SWING_JFRAME,
    SWING_JTABLE,
    SWING_JSCROLL_EDIT,
    SWING_JSCROLL_GRID,
    SWING_EDIT_PANEL,
    SWING_GRID_PANEL,
    HANDLEBAR,
    MAP_COLUMN_POSITION,
    MAP_EDIT_FIELDS,
    BUTTON_GRID_FORM,
    MAP_ATRIB_TO_ALIAS,
    FRAME_QUERY
}
