name: Java - CI - Gradle Build

on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    if: contains( toJson(github), 'devops' ) == false && contains( toJson(github), 'documentation') == false && contains( toJson(github), 'docs') == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Create gradle wrapper
      run: gradle wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
